export const FETCH_SUCCESSFULLY = 'FETCH_SUCCESSFULLY';
export const FETCH_UNSUCCESSFULLY = 'FETCH_UNSUCCESSFULLY';


export const FETCH_GITHUB_SUCCESSFULLY = 'FETCH_GITHUB_SUCCESSFULLY';
export const FETCH_GITHUB_UNSUCCESSFULLY = 'FETCH_GITHUB_UNSUCCESSFULLY';
